### ISSUE TITLE
Logger plus d'info dans SmartLoggerAnalyticsConnectorPlugin

### ISSUE THREAD

**Issue by dslobozian** [KleeGroup/vertigo#100]
Dans la methode `public void add(final AProcess process)` on met dans le jsonObject le nom du process et la durée. Par contre il n'y a pas les mesures `process.getMeasures()`. Voici une proposition `process.getMeasures().forEach((k, v) -> jsonObject.addProperty(k, v));`

**Comment by mlaroche** [comment]
SmartLogger is done for displaying aggregated results, for details on the process use another connector or use the actual log (re-added in 1.0.0)
