### ISSUE TITLE
MessageText default value

### ISSUE THREAD

**Issue by dslobozian** [KleeGroup/vertigo#105]
In `io.vertigo.lang.MessageText.getDisplay()` the defaut value is used only if a message is null. But a message cannot be null (on startup if a key exists there must be a value in the properties files). So my proposal is to replace `if(msg == null)` with `if (StringUtil.isEmplty(msg))`

**Comment by NPi2Loup** [comment]
Work as intended. 
If properties isn't set we take the default message.
