### ISSUE TITLE
Impossible to recover all the locales

### ISSUE THREAD

**Issue by dslobozian** [KleeGroup/vertigo#106]
The class `LocaleManagerImpl` is responsable for charging all the locales (from the configuration file) on startup. the locales are stored in a private list. However, the only publi method is `getCurrentLocale` (used for retrieveing the locale from the session). Could you please add a getter of locales in `LocaleManager`

**Comment by NPi2Loup** [comment]
Locales list is : predefined, static and project dependant. There is no need to dynamically get this list.
