### ISSUE TITLE
Re-implementing getTableName(...) in SearchLoader.

### ISSUE THREAD

**Issue by abalteaux** [KleeGroup/vertigo#107]
in `io.vertigo.dynamox.search.AbstractSqlSearchLoader`, the method `getTableName(final DtDefinition dtDefinition)` needs to be protected only, so that we can re-implement it (when the object name differs from the table name for example).

**Comment by NPi2Loup** [comment]
Work as intended. Indexes are link to a KeyConcept, the KeyConcept is the SQL table name.
If needed the Index Object is another object loaded with a specific request.
