### ISSUE TITLE
[dynamo] Kpr not found

### ISSUE THREAD

**Issue by evernat** [KleeGroup/vertigo#112]
Given the following project with 2 maven modules:
```
ads-core
   src/main/resources/ksp/ads-core.kpr
ads-web
   src/main/resources/ksp/ads.kpr (content is "ads-core.kpr")
```

It seems to me that Vertigo will throw FileNotFoundException (tested on Kasper 4).
In fact, kprUrl.getProtocol() will probably be `file://` (at least in dev), but `new URL("file://..../ksp/ads-core.kpr")` can not be found since /ksp/ads-core.kpr is in a jar file and not unpacked.
See https://github.com/KleeGroup/vertigo/blob/master/vertigo-dynamo-impl/src/main/java/io/vertigo/dynamo/plugins/environment/loaders/kpr/KprLoader.java#L107

kpr and ksp files could always be loaded with getResource(String), and with adding "/" before filename if not present.
In this case, the kpr file will be found in the jar file like this for example:
```java
Thread.currentThread().getContextClassLoader().getResource("/" + "ksp/" + "ads-core.kpr")
```

**Comment by NPi2Loup** [comment]
Kpr files are design to contains relative filename and path. So files in Kpr use the same protocole and path prefix of parent Kpr file.
In order to define multiple Kpr in differente localtion, you juste need to add multiple <resource> tag in your managers.xml

like this : 
```XML
<provider class="io.vertigo.dynamo.plugins.environment.DynamoDefinitionProvider" >
  <resource type="kpr" path="boot/rules/definitions/application-rules.kpr" />
  <resource type="kpr" path="boot/workflow/definitions/application-workflow.kpr" />
  <resource type="kpr" path="boot/definitions/application.kpr" />
</provider>
```

**Comment by evernat** [comment]
ok, it makes sense with Vertigo. (Kasper 4 probably did not have DynamoDefinitionProvider.)
