### ISSUE TITLE
TaskEngineProcBatch.java breaking change

### ISSUE THREAD

**Issue by jordanbenzacken** [KleeGroup/vertigo#114]
In vertigo 1.1.0 a task with the engine TaskEngineProcBatch must only have one parameter of type list.
It could be useful to allow the use of additional parameters that are "constant" for every item in the primary list. In that case it wouldn't be necessary to duplicate this information and modify the list to add it.

For exemple it would be nice to declare such Task : 
```
create Task TK_ASSIGN_PERMISSION_PLATFORM_TO_ROLE_PLATFORM  {    
    className :  "io.vertigo.dynamox.task.TaskEngineProcBatch",    
    request :  "              insert into ROLE_PERMISSION_PLATFORM (rpp_id, rpm_id,  ppm_code) 
VALUES            (nextval('SEQ_ROLE_PERMISSION_PLATFORM'),  #RPM_ID#,  #DTC_PERMISSION_PLATFORM.PPM_CODE#);        ",    
    attribute  RPM_ID {domain:DO_ID,             notNull:"true",     inOut  :"in"},    
    attribute DTC_PERMISSION_PLATFORM    {domain:DO_DT_PERMISSION_PLATFORM_DTC,     notNull:"true",     inOut  :"in"}}
```
Thanks!

**Comment by mlaroche** [comment]
c4d9ad297b3bf645e02949ab38dd0d7474f26e65
