### ISSUE TITLE
FormatterNumber doesn't raise exception when typed value not in mask

### ISSUE THREAD

**Issue by forhanp** [KleeGroup/vertigo#13]
The number formatter has a pattern.
This pattern is not checked when stringToValue is called.
This lead to unexpected behavior when a checking constraint is added to the Domain.
For example : 
User type 3.14159 in a field where only 3 digits is allowed.
The next screen will show a user message with a 3 digits constraints raised and the field in red with the value 3.142.

**Comment by NPi2Loup** [comment]
Formatter is designed to convert a input to the stored value. 
It's not designed to reject correct values.
In your case the simpler way is to defined the formatter with a pattern which keep all input data and to use the constraint to keep the value in accepted range.

Like : 
FormatterNumber "#,##0.00####"
Constraint : ConstraintBigDecimalLength "1,2"
