### ISSUE TITLE
DOCX merger : model in external Jar

### ISSUE THREAD

**Issue by skerdudou** [KleeGroup/vertigo#14]
DOCXMergerPlugin doesn't support if modelFile is in an external jar file
error occurs at DOCXMergerPlugin.java:110

**Comment by NPi2Loup** [comment]
DOCXMergerPlugin take modelFile as a java.io.File. 
java.io.File is a ref to a FileSystem file, it doesn't support file in jar, zip, database and others. We can't support all cases, you should find your model as a ressource (use ResourceManager) then copy it into a local temp file (you could use vertigo FileUtil.copy).
