### ISSUE TITLE
Error in dynamo.domain.util.DtObjectUtil.toString(DtObject dto)

### ISSUE THREAD

**Issue by xuaveneg** [KleeGroup/vertigo#19]
The function does not compute when the two first letters of one of the dto's fields are capitalized.

**Note** : this is due to
```
public static String java.beans.Introspector.decapitalize(String name)
```
called in the line 125 of util.BeanUtil (getPropertyDescriptors)
called in the line 114 of util.BeanUtil (getPropertyDescriptor)
called in the line 56 of util.BeanUtil (getValue)
called in the line 81 of dynamo.domain.metamodel.DataAccessor (getValue)
called in the line 167 of dynamo.domain.util.DtObjectUtil (toString)

which says in its doc

    Utility method to take a string and convert it to normal Java variable name capitalization.
    This normally means converting the first character from upper case to lower case,
    but in the (unusual) special case when there is more than one character and both the
    first and second characters are upper case, we leave it alone.

    Thus "FooBah" becomes "fooBah" and "X" becomes "x", but "URL" stays as "URL".

The *unusual* case isn't managed (the name found which has its first letter capitalized does not match the field name which has its first letter decapitalized)

(source : http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/beans/Introspector.java#Introspector.decapitalize%28java.lang.String%29)

**Comment by NPi2Loup** [comment]
Actually Vertigo doesn't support  field's names like java.beans do. There no plan to improved it yet.
The input of getter method was always field name in DtDefinition.
Field names must be in constant, and getter method is the camel cased traduction

Ex : 
* MY_FIELD -> getMyField()
* URL -> getUrl()
* FIELD_1 -> getField1()
* FIELD1 -> __NotSupportedError__
* MY__FIELD -> __NotSupportedError__
