### ISSUE TITLE
[core][space] Cannot use an action in url

### ISSUE THREAD

**Issue by durandx** [KleeGroup/vertigo#20]
In compliance with https://github.com/KleeGroup/vertigo/wiki/routes i want to add a route with an action, for example : /commandes/123/export()

I got the following error 
```
urn de définition EP_XX_XXX() doit matcher le pattern [A-Z0-9_]{3,60}([$][A-Z0-9_]{3,60})?
```

<img src="http://ljdchost.com/Vc2dQLV.gif"/>

PS : I use the 0.8.1 version of Vertigo

**Comment by NPi2Loup** [comment]
After some testing, it seems parentheses are not supported in route path by java-spark.
Doc should be updated.
