### ISSUE TITLE
Access to DtDefinition in UiListModifiable ?

### ISSUE THREAD

**Issue by xuaveneg** [KleeGroup/vertigo#22]
Hi again,

I want to put a list on my page, where only the last element can be editable.

When I try to use a `ContextList` to do this, everything is okay, except that when the user enters an invalid input, the following error
```Java
java.lang.UnsupportedOperationException: This list contains UiObject only. If objects are modifiable please use UiListModifiable instead of this one.
```
appears in `UiListUnmodifiable.indexOf (UiListUnmodifiable: 104)`.

... So I tried with `ContextListModifiable`, this time, everything is okay, except that I can't use the label of my objects from `UiUtil` because in `UiUtil.getDtField`, line 130, the `contextObject` is expected to be a `UiObject` or a `AbstractUiList`, and `UiListModifiable` is not a child of `AbstractUiList`.

I tried different ways to solve my problem, and I think the best way is to add an access to the `DtDefinition` of a `UiListModifiableObject`, like
```Java
public DtDefinition getDtDefinition() {
	return dtList.getDefinition();
}
```
and adapt `UiUtil.getDtField` to make it accept `UiListModifiable` objects.

Maybe there is a better solution to achieve what I want to do, but either way, I think it's absurd to not be able to access the `DtDefinition` of a `UiListModifiable` as it is in a `AbstractUiList`.

**Comment by NPi2Loup** [comment]
Yes, your are right. getDtDefinition should be in UiList interface.
It should be fixed.
