### ISSUE TITLE
[DefaultListFilterBuilder] Bad request sent to ES for criteria after a date :   var:[#val# TO *]

### ISSUE THREAD

**Issue by durandx** [KleeGroup/vertigo#24]
In the listFilterBuilderQuery when I try to filter on a date range with a value after a given date, the request generated to ES is not valid __if the value is null__:

In my FacecetedQueryDefinition I have:
```
listFilterBuilderQuery : "NOM_NAISSANCE:#+nomNaissance*# PRENOM:#+prenom*# DATE_MODIFICATION_DEPUIS:[#dateModificationDepuis# TO *]"
```

Here __dateModificationDepuis is null__

<pre><code>
org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query], all shards failed; shardFailures {[s96PAHrJTA-Gh58b8S-Wcg][idx_personne][0]: 
SearchParseException[[idx_personne][0]: from[0],size[50]: Parse Failure [Failed to parse source [{"from":0,"size":50,"query":{"query_string":{"query":" +(NOM_NAISSANCE:(+Nom*) PRENOM:(+prenom*)  TO *])","lowercase_expanded_terms":false,"analyze_wildcard":true}},"fields":"FULL_RESULT","highlight":{"highlight_filter":true,"number_of_fragments":3,"fields":{"*":{}}}}]]]; 
nested: QueryParsingException[[idx_personne] Failed to parse query [ +(NOM_NAISSANCE:(+Nom*) PRENOM:(+prenom*)  TO *])]]; nested: ParseException[Cannot parse ' +(NOM_NAISSANCE:(+Nom*) PRENOM:(+prenom*)  TO *])': Lexical error at line 1, column 49.  Encountered: "]" (93), after : ""]; nested: TokenMgrError[Lexical error at line 1, column 49.  Encountered: "]" (93), after : ""]; }{[s96PAHrJTA-Gh58b8S-Wcg][idx_personne][1]: SearchParseException[[idx_personne][1]: from[0],size[50]: Parse Failure [Failed to parse source [{"from":0,"size":50,"query":{"query_string":{"query":" +(NOM_NAISSANCE:(+Nom*) PRENOM:(+prenom*)  TO *])
</pre></code>

**Comment by NPi2Loup** [comment]
Could you which result do you expect ?

I think about theses : 
```
TEST_RANGE:[#start# TO #end#] 
notNull, notNull => TEST_RANGE:[0 TO 10]
null, notNull    => TEST_RANGE:[* TO 10]
notNull, null    => TEST_RANGE:[0 TO *]
null, null       => <empty string>
```
```
TEST_RANGE:[#start# TO 10] 
notNull  => TEST_RANGE:[0 TO 10]
null     => TEST_RANGE:[* TO 10]
```
```
TEST_RANGE:[#start# TO *] (we don't want that * has a specfic behavior other than 10)
notNull  => TEST_RANGE:[0 TO *]
null     => TEST_RANGE:[* TO *] (accepted ?)
```

**Comment by durandx** [comment]
```TEST_RANGE:[#start# TO *] (we don't want that * has a specfic behavior other than 10)
notNull  => TEST_RANGE:[0 TO *]
null     => TEST_RANGE:[* TO *] 
```
* TO * seems accepted

**Comment by NPi2Loup** [comment]
Ok. You found the fine way with the default value.
We will update documentation in DefaultListFilterBuilder.

**Comment by durandx** [comment]
Having an assert preventing that case could had been nice to have ...
