### ISSUE TITLE
Access context parameters in vertigo

### ISSUE THREAD

**Issue by a-peyre** [KleeGroup/vertigo#25]
In linkit, using the kasper framework, I could access context parameters in the java code:

connection = ((ApplicationState) Container.getApplicationState()).getAS400ConnectionProvider().obtainConnection().getJdbcConnection();

the as400connection provider was initialized (in the applicationState) at the start of the application, using a context parameter declared in an xml file.

How can i perfom a similar task in vertigo?

**Comment by a-peyre** [comment]
in the source, we saw a class called datasource connection provider plugin, but this class creates a connexion using an existing url. I would like to store that url in the context (like we did with kasper). Therefore I'me still wondering how I can read context parameters

**Comment by NPi2Loup** [comment]
The simpler way is to register a DataSourceConnectionProviderPlugin with its parameter in your ComponentContainer, and then Inject it into a dedicated TaskEngine.
To register the DataSourceConnectionProviderPlugin as a component with a specific name, you must use an initializer, you can't do it yet from managers.xml

**Comment by a-peyre** [comment]
More scpecifically, my question was :

how should i load my datasource url from the context.xml file, into my componentContainer
