### ISSUE TITLE
#25, #26 use alternate datasource on vertigo

### ISSUE THREAD

**Issue by a-peyre** [KleeGroup/vertigo#27]
I checked the web on how to reopen a closed issue on github. I did not find any usefull advice.

I further researched how to declare alternate connections.

in the web.xml file I have the following

  ```
<context-param>
    <param-name>boot.db.source</param-name>
    <param-value>java:/comp/env/jdbc/DataSource</param-value>
  </context-param>
  <context-param>
    <param-name>boot.db.classname</param-name>
    <param-value>io.vertigo.dynamo.impl.database.vendor.sqlserver.SqlServerDataBase</param-value>
  </context-param>
```

I also have a db.xml file containing te following

```
<?xml version =	'1.0' encoding = 'UTF-8'?>
<config>
	<module name="linkit-env">
		<component api="SqlDataBaseManager" class="io.vertigo.dynamo.impl.database.SqlDataBaseManagerImpl">
	        <plugin class="io.vertigo.dynamo.plugins.database.connection.datasource.DataSourceConnectionProviderPlugin">
		    	<param name="source" value="{boot.db.source}" />
	            <param name="classname" value="{boot.db.classname}" />
	        </plugin>
		</component>
	</module>
</config>
```

As I understand it, I should set additional connection parameters in the web. xml file, something like this:

  ```
<context-param>
    <param-name>boot.db.source</param-name>
    <param-value>java:/comp/env/jdbc/DataSource</param-value>
  </context-param>
  <context-param>
    <param-name>boot.db.classname</param-name>
    <param-value>io.vertigo.dynamo.impl.database.vendor.sqlserver.SqlServerDataBase</param-value>
</context-param>
<context-param>
    <param-name>newConnection.source</param-name>
    <param-value>java:/**********DataSource</param-value>
  </context-param>
  <context-param>
    <param-name>newConnection.classname</param-name>
    <param-value>***************.SqlServerDataBase</param-value>
  </context-param>
```

What I do not get is what I should create in the db.xml file.

Should I add a whole new module, simply a new connection manager, or simply add a second plugin to the existing connection manager.

I realise that at least part of the answer is contained in your previous message, but I am rather confused and would appreciate more precise guidance

**Comment by a-peyre** [comment]
I have been digging a bit more into vertigo. From what I can figure out now, the SqlDataBaseManager can only get a single SqlConnectionProviderPlugin.

Therefore I would need to declare a new connection manager. However, the SqlDataBaseManager class is final due to the injection constraints.

I was thinking of creating an alternate SqlDataBaseManager that I would call for example AS400SqlDataBaseManager. I could then inject this manager into my AS400TaskEngine.

Is this the right approach? That seems a bit akward to me as it implies creating a duplicate of the existing SqlDataBaseManager.

Moreover, as I nedd to connect to four different sistems, that means I would need to copy paste the SqlDataBaseManager code three times which .

**Comment by NPi2Loup** [comment]
Next release add a support of multiple sqlConnectionProvider.
What is your current version ?

**Comment by a-peyre** [comment]
Merci pour cette réponse
 
nous utilisons vertigo 0.8.2
 
Alexandre

**Comment by NPi2Loup** [comment]
Version 0.8.3 added a first step in multidatabase support.
You must kept one and only one default ConnectionProviderPlugin without name.

Now you could put multiple named ConnectionProviderPlugins in DataBaseManager.
A extended TaskEngine in your project could get the connectionProvider needed.
