### ISSUE TITLE
[Studio] Add generated const for static masterdata

### ISSUE THREAD

**Issue by NPi2Loup** [KleeGroup/vertigo#31]
1- alter Ksp syntax to register values for static masterdata
alter FOLDER_STATE { 
  constValue EDITING: { DST_CD:"EDI", LABEL:"Editing"}, 
  constValue VALIDATED: { DST_CD:"VAL", LABEL:"Validated"}, 
  constValue ARCHIVED: { DST_CD:"ARC", LABEL:"Archived"}
}

2- generate inserts SQL files

3- generate const in some classes
Should be useable on SQL request, java services for setter or equals
Should be Enum or String ?

**Comment by Jean-MichelForhan-KLEE** [comment]
an Enum allows for automated checks between database entries and usable values in Java

**Comment by NPi2Loup** [comment]
Fixed by b8ca88bb324583ad8915f33e64ad914a770afe2d
