### ISSUE TITLE
[Studio] Add generated route js useable by Focus

### ISSUE THREAD

**Issue by NPi2Loup** [KleeGroup/vertigo#32]
1- @pierr  Define js routes definitions syntax (Verb, Prefix?, Route). Should define routes only or services with parameters ?

2- Add js routes generator

**Comment by pierr** [comment]
https://github.com/KleeGroup/focus-demo/blob/master/api/src/main/java/rodolphe/demo/webservices/movie/MovieWebServices.java

**Comment by pierr** [comment]
https://github.com/KleeGroup/focus-demo/blob/master/ui/app/config/server/movie.js

**Comment by pierr** [comment]
The function we use to generate url is here https://github.com/KleeGroup/focus-core/blob/develop/src/util/url/builder.js
The signature is 
```javascript
function(urlWithParams, method){
  return function({bodyData, urlData})
}
```

**Comment by NPi2Loup** [comment]
```jsx
function(WsParam)
function({param1,param2}){
}
```

**Comment by NPi2Loup** [comment]
https://gist.github.com/pierr/50af3352c6c9038e6c41

**Comment by NPi2Loup** [comment]
Done
