### ISSUE TITLE
A discuter : stockage de fichiers temporaires

### ISSUE THREAD

**Issue by Jerom138** [KleeGroup/vertigo#34]
Il serait intéressant, en particulier vis à vis de l'upload de fichiers (remontés au serveur et stockés temporairement avec une key, en attendant d'être sauvegardés avec l'objet soumis dans un second temps...), de pouvoir gérer proprement le stockage des fichiers temporaires.

En pouvant, par exemple, paramétrer sur le storeManage un storePlugin par définition fileInfo. Ainsi on pourrait utiliser un plugin de stockage complet pour les fichiers sauvegardés et un autre spécifique pour les fichiers temporaires. (A voir si les fichiers temporaires ne doivent pas être en fait déjà stockés en prévision d'être utilisé à la sauvegarde, auquel cas c'est la question du nettoyage des fichiers non référencés qui se pose...).

Idéalement, un deamon de nettoyage des fichiers temporaires pourrait être aussi mis en place avec ce "TempFileStorePlugin", pour ne pas devoir être écrit sur chaque projet.

**Comment by pierbrisson** [comment]
:+1:
