### ISSUE TITLE
[Dynamo] Utilisation du cache sur la recherche filtrée sur un champ avec le broker

### ISSUE THREAD

**Issue by Jerom138** [KleeGroup/vertigo#38]
J'ai l'impression que la fonction getListByDtField du DAO ne permet pas un fonctionnement correct avec le cache.
Si par exemple, je cherche un pays par son code ISO "FR" :
- la première fois, il remonte par un select, de la base de données, la liste d'un pays "France",
- puis il met correctement en cache non seulement le pays "France" avec son URI comme clé,
- ainsi que la liste (cf. CacheData.putDtList) avec son URI (basé sur l'objet criteria de la recherche) comme clé.

Si je refais la même recherche, il ne va chercher dans le cache qu'à retrouver l'URI de critère de recherche (code ISO FR).
Le problème est alors que même avec la même recherche (code ISO "FR"), c'est un nouveau criteria (avec un id différent) qui est construit.
La recherche en cache ne remonte rien et on attaque à nouveau la base.

Du coup, pour ces cas, je me demande si on ne remplit pas inutilement et indéfiniment le cache avec des listes qui ne seront plus jamais utilisées ?
Et surtout, est ce qu'on ne pourrait pas imaginer une solution pour retrouver, en utilisant le broker et le cache, un élément d'une liste de réf à partir de son code ?

**Comment by Jerom138** [comment]
Pour le cas précis remonté ci-dessus, il a suffit de créer (générer avec Eclipse) la méthode hashCode()  de l'objet io.vertigo.dynamo.store.criteria.FilterCriteria plutôt que de laisser le equals par défaut sur les Object.
A voir, s'il ne faudrait pas gérer de façon homogène à celle-ci, les GroupCriteria, et autres...

**Comment by NPi2Loup** [comment]
C'est fait. Merci.
