### ISSUE TITLE
[Vega] dataList et totalCount hors Elasticsearch

### ISSUE THREAD

**Issue by Jerom138** [KleeGroup/vertigo#40]
Est-ce que le [PaginatorAndSortWebServiceHandlerPlugin](http://github.com/KleeGroup/vertigo/blame/develop/vertigo-vega-impl/src/main/java/io/vertigo/vega/plugins/webservice/handler/PaginatorAndSortWebServiceHandlerPlugin.java) ne pourrait/devrait pas renvoyer un objet avec un attribut "dataList", ainsi qu'un attribut "totalCount", plutôt que seulement la DtList et le totalCount dans le Header HTTP ?
L'idée serait d'être homogène avec ce que fait le [GoogleJsonEngine](http://github.com/KleeGroup/vertigo/blame/develop/vertigo-vega-impl/src/main/java/io/vertigo/vega/engines/webservice/json/GoogleJsonEngine.java#L330) avec le [FacetedQueryResultJsonSerializer](http://github.com/KleeGroup/vertigo/blame/develop/vertigo-vega-impl/src/main/java/io/vertigo/vega/engines/webservice/json/GoogleJsonEngine.java#L330) pour les résultats de recherche ES.
Ainsi, sur une utilisation de Focus-components côté IHM, il ne serait pas nécessaire de réécrire un parser customisé pour reformater le retour lorsque l'on utilise un composant List sans utiliser Elasticsearch pour la recherche...

**Comment by Jerom138** [comment]
@pierr

**Comment by NPi2Loup** [comment]
Ce choix a été fait avant l'utilisation FacetedQueryResult. Mais on s'était quand même posé la question.
La raison était que le WebService qui retourne une liste devait avoir l'api la plus naturelle possible.
Et pour un WebService qui retourne une liste, il est beaucoup plus naturel de retourne une liste dans le body et les méta données en HeaderHttp.
Ex twitter : https://dev.twitter.com/rest/reference/get/statuses/user_timeline

**Comment by Jerom138** [comment]
Alors peut-être une autre annotation spécifique pour utilisation avec Focus en front ?
L'idée étant toujours d'avoir le moins de chose possible à écrire spécifiquement sur les applications, alors qu'elles utilisent, de façon classique, chacun des 2 farmeworks Vertigo et Focus...

**Comment by NPi2Loup** [comment]
Sur le fond, on est d'accord.
Sur la façon de faire : a discuter avec Focus.

**Comment by Jerom138** [comment]
[A traiter côté Focus](https://github.com/KleeGroup/focus-components/issues/651) : un fetch spécifique sera mis à disposition pour parser correctement le format remonté par les recherches sans Elasticsearch.
