### ISSUE TITLE
[Dynamo] Possibilité de définir des listes de type primitif dans les DtObject

### ISSUE THREAD

**Issue by Jerom138** [KleeGroup/vertigo#41]
Il sera pratique de pouvoir définir parmi les attributs d'un DTO, des attributs typés "liste de type primitif (String ou Long)".
La principale application concerne les multi sélections. Les composants Focus permettant la multisélection traite et renvoie une liste d'identifiants (ce qui parait cohérent avec la sélection simple qui retourne bien l'identifiant de la sélection...).
Il est actuellement nécessaire de contourner ce manque de Vertigo en retournant une liste de DtObject contenant un attribut identifiant... puis de faire une transformation côté js pour injecter ces données aux composants.
Et d'autre part, le webservice qui récupère les données soumises doit utiliser un innerBodyParam typé List<Long>, ... ce qui devient vite moche quand un formulaire contient plusieurs champs multivalués.

**Comment by NPi2Loup** [comment]
Fixed by 1f72dd6a12b9b3e70141cc6eccde8194541e4496

A field could have a domain multiple.
Warning : a field like this must be non persistent.

Example: 
```Json
create Domain DO_MULTIPLE_LABEL {
   dataType : String
   formatter : FMT_DEFAULT
   multiple : true
}
```
