### ISSUE TITLE
[dynamo.domain.model] Please provide a java 8 compliant Collectors class for DtList

### ISSUE THREAD

**Issue by durandx** [KleeGroup/vertigo#43]
Please provide a java 8 compliant Collectors class for DtList.

Actually to get a DtList using stream, i need to to do the following pattern:

```java
		final List<Structure> structures = myList.stream().map(myMap).collect(Collectors.toList());
		final DtList<Structure> dtList = new DtList(Structure.class);
		dtList.addAll(structures);
```
Please provide a Vertigo compliant Collectors for DtList (a VCollectors).

**Comment by NPi2Loup** [comment]
Right now, there is no plan to support Java 8 exclusives functions. 
Many projects currently in devlopment phase still use Java 7, so we keep Vertigo compatible with Java 7. 
You could encapsulate your DtList into a projet specific List implementation.

**Comment by NPi2Loup** [comment]
If needed, comment to reopen.

**Comment by durandx** [comment]
No need, I've done it on my own.


```java
  dtList = myList.stream().map(myMap).collect(VCollectorsLite.toList(Structure.class));
```


<img src="http://i.giphy.com/d2Z7lyGSWm5drlV6.gif" />
