### ISSUE TITLE
[vertigo]  allow workOnkeyConcept method to return KeyConcept

### ISSUE THREAD

**Issue by Jean-MichelForhan-KLEE** [KleeGroup/vertigo#48]
When updating a keyconcept or related objects, we need to:
- call workOnkeyConcept to lock the keyconcept on which we work
- get the keyconcept  to do security check with the latest available data
- get the other needed data

Currently, the workOnkeyConcept method return void while doing a call to database. This means that there is at least 2 database calls when trying to make things rights.
If the workOnkeyConcept method returns the keyconcept, it would allow to:
- ensure that the keyconcept is properly locked
- reduce database calls
- make easier in code to spot taht lock is correctly made when working on key concept

**Comment by NPi2Loup** [comment]
Done
