### ISSUE TITLE
[Vertigo] ES : Characters are not correctly escaped

### ISSUE THREAD

**Issue by durandx** [KleeGroup/vertigo#49]
# Actual behaviour
Values sent to ES are not properly escaped  (maybe this can lead to big security threat like injecting)
Example of character not propertly escaped like ```^ [ : (```. 

I can even enter expression like ```OR *``` in a criteria, this will be executed as ```SECURITY_ID:(ID OR *)```
If the expression is not valid this lead to an exception thrown by vertigo.
If the expression is valid, the request is simply executed 'as it' in ES (I mean you can inject all the expression you want).

# Expected behaviour
Please escape all the ES syntax in values sent to ES.

# Versions
Vertigo: 0.9.0

**Comment by NPi2Loup** [comment]
Right now, user queries aren't escaped to authorized advanced usage of Lucene QueryString syntax. 
_(The reserved characters are: + - = && || > < ! ( ) { } [ ] ^ " ~ * ? : \ / )_

To ensure security, you must use the SearchQueryBuilder right:
```Java
SearchQuery searchQuery = new SearchQueryBuilder(<userQueryUnescapedString>)
    .withSecurityFilter(<mandatoryAndNotModifiableByUserSecurityFilter>)
    .build();
```
This way the security filter can't be overrided by users. 
SECURITY_ID should never be a user entry, it comes from user security context.

Note that ``SECURITY_ID:* OR +SECURITY_ID:ID OR *:*`` keep SECURTY_ID=ID as mandatory whatever there is before or after.

However, we may look to add a parameter of QueryDefinition to escape all reserved char in user query.

**Comment by NPi2Loup** [comment]
Added in v0.9.1.
We added a new syntax to this issue.

In queryDefinition you could use an query operator :    
* ``#FIELD_1#?(escapeReserved)`` => escape reserved syntaxe in FIELD_1  
* ``#FIELD_2#?(removeReserved)`` => remove reserved syntaxe in FIELD_2   


Reserved word are : ``+ - = && || > < ! ( ) { } [ ] ^ " ~ * ? : \ / or and``

**Comment by NPi2Loup** [comment]
Added a better error message in case of ElasticSearch parsing error
