### ISSUE TITLE
[dynamox] DslListFilterBuilder usage of {escapeReserved,removeReserved} with boost

### ISSUE THREAD

**Issue by durandx** [KleeGroup/vertigo#57]
How to Use the ```?(escapeReserved)``` syntaxe with a boost ?

I've tryied the following syntaxe and got an exception in both case (Syntaxe error, or reserved expression prohibited) : 
```
FIELD:#criteria*#^2?(escapeReserved)
```
```
FIELD:#criteria*#?(escapeReserved)^2
```

I've tried with the following values  : ```and``` ```or```

Vertigo : 0.9.1

**Comment by NPi2Loup** [comment]
It's link to the 'and' 'or' detection.
We looks for spaces before and after these keywords.
