### ISSUE TITLE
[Search] Empty facet value should not be returned by the server

### ISSUE THREAD

**Issue by Tommass** [KleeGroup/vertigo#61]
## Je suis confronté à ce cas

![image](https://cloud.githubusercontent.com/assets/5349745/13397307/a29797e6-def9-11e5-83fd-f2bd2723d16d.png)

Le serveur me renvoit une facette 'Titre' avec 1 seule valeur contenant 1 élements et toutes les autres à zéro.
Ainsi qu'une facette 'terme' avec toutes ces valeurs à zero.

## Comportement attendu

Dans les 2 cas mentionnés ci-dessus, le serveur ne doit pas me retourner de facette, cela n'a pas de sens. Cela n'a aucune valeur ajoutée pour l'utilisateur, et côté front-end elle ne me sert à rien. Enfin, affichée, elle apporte de la confusion.

**Comment by durandx** [comment]
Si je ne dis pas de bêtise : "it's not a bug, it's a feature". Ce cas doit se produire uniquement pour les facette "Range". Je pense qu'il faudrait tout de même avoir un comportement uniforme entre les facettes à valeur et les facettes range...

**Comment by NPi2Loup** [comment]
Comme l'a indiqué @durandx , c'est un choix d'affichage d'éliminer les facets à 0 ou pas.
