### ISSUE TITLE
[VEGA] Optional inner body param cannot be a DtObject

### ISSUE THREAD

**Issue by samuel-22** [KleeGroup/vertigo#76]
`public class MyFilter implements DtObject {`
`    ....  `
`}  `
  
`@POST("/myWebService")`  
`public void myWebService(@InnerBodyParam("filters") final Option<MyFilter> filters) {  `
`    ....  `
`}  `

Rise this exception if the request body doesn't contain a filters object : 
`java.lang.NullPointerException: InnerParam not found : class com.exemple.MyFilter :InnerBody:filters
at io.vertigo.lang.Assertion.checkNotNull(Assertion.java:69)
at io.vertigo.vega.plugins.webservice.handler.converter.DtObjectJsonConverter.populateWebServiceCallContext(DtObjectJsonConverter.java:69)`

No problem if MyFilter class implements directly Serializable.

**Comment by NPi2Loup** [comment]
WebServices API should not use Optional too much. They are use to declared and fixed a API contract, optional add some flexibility but add fuzzy too. 
In your case, think about use 2 WebServices, one with and one without your optional object.

However, current error 500 are a bug, and should be fixed.
