### ISSUE TITLE
Problème d'indexation unitaire ES en version 9.3

### ISSUE THREAD

**Issue by Jean-MichelForhan-KLEE** [KleeGroup/vertigo#78]
suite à la séparation des Dtobjects en entity (persisté) et autre (non persisté), le type de champ clé n'est plus autorisé sur les DtObject non persisté.
Or l'indexation Elastic search se base sur la présence d'un champ clé sur le dto afin d'avoir l'uri de l'objet à remplacer.

Et la tache de reindexation unitaire utilise cette propriété:
ReindexTask.urisToListFilter contient la ligne de code suivante:
final String indexIdFieldName = searchIndexDefinition.getIndexDtDefinition().getIdField().get().getName();

qui indique clairement que l'on s'attend à avoir un champ clé sur le Dtobject.

**Comment by NPi2Loup** [comment]
Oui, ce pb a été identifié et corrigé : 75e87f0ec227a93a8315a66ef4bfebbdf3115727
Livrer dans la prochaine livraison
