### ISSUE TITLE
[PerformanceMetricEngine] Create new Transaction in case of the query failed

### ISSUE THREAD

**Issue by Papisco** [KleeGroup/vertigo#81]
Cas particulier de PostgreSQL en cas d'erreur on ne peut plus travailler avec la transaction courante.
 
 http://stackoverflow.com/questions/10399727/psqlexception-current-transaction-is-aborted-commands-ignored-until-end-of-tra

**Comment by NPi2Loup** [comment]
Porte sur Studio
