### ISSUE TITLE
Swagger don't detect webapp context prefix

### ISSUE THREAD

**Issue by NPi2Loup** [KleeGroup/vertigo#88]
Swagger don't detect webapp context prefix.
If webservices url is : http://localhost:8080/myApp/api/testWebServices
Swagger call : http://localhost:8080/api/testWebServices

**Comment by NPi2Loup** [comment]
Should fix prefixUrl l:
```Java
	@SessionLess
	@AnonymousAccessAllowed
	@GET("/swaggerApi")
	public Map<String, Object> getSwapperApi(final HttpServletRequest request) {
		//compute contextPath + servletPath - current Ws url
		// Spark override getRequestURI and removed contextPath from it, so we put it manualy
		final String prefixUrl = request.getContextPath()
				+ request.getRequestURI().substring(0, request.getRequestURI().indexOf("/swaggerApi"));
		return new SwaggerApiBuilder()
				.withContextPath(prefixUrl)
				.withWebServiceDefinitions(Home.getApp().getDefinitionSpace().getAll(WebServiceDefinition.class))
				.build();
	}
```

**Comment by durandx** [comment]
File to patch : io/vertigo/vega/impl/webservice/catalog/SwaggerWebServices.java
With content : https://raw.githubusercontent.com/KleeGroup/vertigo/a07d963abe3aa05e58972e6fbcb6cf4116cf9cab/vertigo-vega-impl/src/main/java/io/vertigo/vega/impl/webservice/catalog/SwaggerWebServices.java
