### ISSUE TITLE
Let developer to indicate it's own name of PAO

### ISSUE THREAD

**Issue by mdabo** [KleeGroup/vertigo#91]
Writing a ksp (services), it will be fine to let developer to define the name of it's pao.
When the autogenaration take the last word of the declared package name, it's possible to have multiple PAO with the same name. Which may be confusing in the java code.
We can take by default the package name for the  PAO but take the declared name when exist

**Comment by NPi2Loup** [comment]
This choice is based on our naming convention.
The last word in declared package should be the business module's name. 
And business module are should be unique.
like : 
```
fr.client.app.dao.consumer
fr.client.app.dao.admin
fr.client.app.dao.common
```

If you do so, generated PAO are unique
```
ConsumerPAO
AdminPAO
CommonPAO
```

**Comment by mlaroche** [comment]
See upper comment. You should follow our naming conventions.
